name = "a0b_timer"
description = "A0B Timer"
version = "0.2.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "timer"]

project-files = ["gnat/a0b_timer.gpr"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_callbacks = "*"
a0b_time = "*"
a0b_timer_platform = "0.1.0"
